export default [
  {
    inputs: [{ internalType: "address", name: "target", type: "address" }],
    name: "AddressEmptyCode",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "AddressInsufficientBalance",
    type: "error",
  },
  { inputs: [], name: "AlreadyExist", type: "error" },
  { inputs: [], name: "ETHTransferFailed", type: "error" },
  { inputs: [], name: "FailedInnerCall", type: "error" },
  { inputs: [], name: "IncorrectArrayLength", type: "error" },
  {
    inputs: [
      { internalType: "address[]", name: "assets_", type: "address[]" },
      { internalType: "address[]", name: "expectedAssets_", type: "address[]" },
    ],
    name: "IncorrectAssetsList",
    type: "error",
  },
  { inputs: [], name: "IncorrectInitParams", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "ltv", type: "uint256" }],
    name: "IncorrectLtv",
    type: "error",
  },
  { inputs: [], name: "IncorrectMsgSender", type: "error" },
  { inputs: [], name: "IncorrectZeroArgument", type: "error" },
  { inputs: [], name: "InsufficientBalance", type: "error" },
  { inputs: [], name: "InvalidInitialization", type: "error" },
  { inputs: [], name: "NotExist", type: "error" },
  { inputs: [], name: "NotFactory", type: "error" },
  { inputs: [], name: "NotGovernance", type: "error" },
  { inputs: [], name: "NotGovernanceAndNotMultisig", type: "error" },
  { inputs: [], name: "NotInitializing", type: "error" },
  { inputs: [], name: "NotMultisig", type: "error" },
  { inputs: [], name: "NotOperator", type: "error" },
  { inputs: [], name: "NotPlatform", type: "error" },
  { inputs: [], name: "NotTheOwner", type: "error" },
  { inputs: [], name: "NotVault", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint256", name: "value", type: "uint256" }],
    name: "TooLowValue",
    type: "error",
  },
  { inputs: [], name: "WaitForNewPeriod", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "platform",
        type: "address",
      },
      { indexed: false, internalType: "uint256", name: "ts", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "block",
        type: "uint256",
      },
    ],
    name: "ContractInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "periodEnded",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalStblRevenue",
        type: "uint256",
      },
    ],
    name: "EpochFlip",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "unitIndex",
        type: "uint256",
      },
      { indexed: false, internalType: "string", name: "name", type: "string" },
      {
        indexed: false,
        internalType: "address",
        name: "feeTreasury",
        type: "address",
      },
    ],
    name: "NewUnit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "unitIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "stblGot",
        type: "uint256",
      },
    ],
    name: "ProcessUnitRevenue",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "periodEnded",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "unitName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "stblRevenue",
        type: "uint256",
      },
    ],
    name: "UnitEpochRevenue",
    type: "event",
  },
  {
    inputs: [],
    name: "CONTROLLABLE_VERSION",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VERSION",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "aavePools",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "activePeriod",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum IRevenueRouter.UnitType",
        name: "unitType",
        type: "uint8",
      },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "address", name: "feeTreasury", type: "address" },
    ],
    name: "addUnit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "createdBlock",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPeriod",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "platform_", type: "address" },
      { internalType: "address", name: "xStbl_", type: "address" },
      { internalType: "address", name: "feeTreasury_", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "unitIndex", type: "uint256" }],
    name: "pendingRevenue",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingRevenue",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platform",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "processFeeAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "vault", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "processFeeVault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "unitIndex", type: "uint256" }],
    name: "processUnitRevenue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "processUnitsRevenue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address[]", name: "pools", type: "address[]" }],
    name: "setAavePools",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "updatePeriod",
    outputs: [{ internalType: "uint256", name: "newPeriod", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
];
